/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoTokenizersRouteImport } from './routes/demo-tokenizers'
import { Route as DemoMathRouteImport } from './routes/demo-math'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiChatServerRouteImport } from './routes/api/chat'

const rootServerRouteImport = createServerRootRoute()

const DemoTokenizersRoute = DemoTokenizersRouteImport.update({
  id: '/demo-tokenizers',
  path: '/demo-tokenizers',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMathRoute = DemoMathRouteImport.update({
  id: '/demo-math',
  path: '/demo-math',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatServerRoute = ApiChatServerRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-math': typeof DemoMathRoute
  '/demo-tokenizers': typeof DemoTokenizersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-math': typeof DemoMathRoute
  '/demo-tokenizers': typeof DemoTokenizersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-math': typeof DemoMathRoute
  '/demo-tokenizers': typeof DemoTokenizersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo-math' | '/demo-tokenizers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo-math' | '/demo-tokenizers'
  id: '__root__' | '/' | '/demo-math' | '/demo-tokenizers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoMathRoute: typeof DemoMathRoute
  DemoTokenizersRoute: typeof DemoTokenizersRoute
}
export interface FileServerRoutesByFullPath {
  '/api/chat': typeof ApiChatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/chat': typeof ApiChatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/chat': typeof ApiChatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/chat'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/chat'
  id: '__root__' | '/api/chat'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiChatServerRoute: typeof ApiChatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-tokenizers': {
      id: '/demo-tokenizers'
      path: '/demo-tokenizers'
      fullPath: '/demo-tokenizers'
      preLoaderRoute: typeof DemoTokenizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-math': {
      id: '/demo-math'
      path: '/demo-math'
      fullPath: '/demo-math'
      preLoaderRoute: typeof DemoMathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoMathRoute: DemoMathRoute,
  DemoTokenizersRoute: DemoTokenizersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiChatServerRoute: ApiChatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
